### ISSUE TITLE
Table of contents in Read the Docs 

### ISSUE THREAD

**Issue by faird42** [DCAN-Labs/nda-abcd-collection-3165#1]
The Table of Contents in Read the Docs is set to external links. Would suggest adding another 'Resource' Tab with the links in it, or potentially add them to the margins, so it is clear what is actually the Table of Contents. Also these initial links take you directly of the site.

**Comment by ericearl** [comment]
@faird42 Apologies, but I need some clarification.  Are you talking about the header at the top of each page that links off to those specific websites?  The header may be irrelevant at this point and more distracting than helpful.  I feel like it made more sense when these were PDF documents.

I will add a small warning for now in each page's header about how any links contained within the docs takes you off the docs site unless you choose to open it in a new tab.

**Comment by faird42** [comment]
I would just put them in the margins at the side under a 'useful links' heading or something. They are useful links but don't want them to be confused with the actual table of contents.

**Comment by ericearl** [comment]
@faird42 How does this look?  Does this satisfy the need?  Make sure to refresh your browser if you visit a page and the header is still present.

https://collection3165.readthedocs.io/en/stable/useful/

Thanks!
~Eric

**Comment by ericearl** [comment]
Closing this issue unless further comments arise.
