### ISSUE TITLE
Fieldmap's "IntendedFor" field

### ISSUE THREAD

**Issue by tommyng730** [DCAN-Labs/nda-abcd-collection-3165#3]
never mind-- I found an explanation for my original question here about fmaps here-- 

https://github.com/DCAN-Labs/nda-abcd-collection-3165/blob/ee6f1b1894a157699e43769f411f27555382bec4/docs/inputs.md

**Comment by ericearl** [comment]
@tommyng730 I saw your original message and I am curious how many field maps have empty IntendedFor list fields in their JSONs.  I don't think we intended that IntendedFor behavior so I am leaving this issue open for that reason until we can be certain why there are any empty IntendedFor fields in field map data anywhere.  I think it's fine in BIDS to omit an IntendedFor field in a field map if it's not intended for use.

Also, here's a cleaner link to that documentation you were reading:
https://collection3165.readthedocs.io/en/stable/inputs/#8-bids-field-map-intendedfor-metadata

**Comment by tommyng730** [comment]
Hi Eric,

From what I saw, I think most participants have 10 field maps and usually 8 of them have empty Intendedfor fields in their JSONs.

**Comment by ericearl** [comment]
@perronea I would like to migrate this issue to https://github.com/ABCD-STUDY/nda-abcd-collection-3165 if you still agree it's an issue.

**Comment by ericearl** [comment]
Migrated to: https://github.com/ABCD-STUDY/nda-abcd-collection-3165/issues/4
